### ISSUE TITLE
`mock` is either missing from requirements or is an omitted testing module.

### ISSUE THREAD

**Issue by OAuthBringer** [boldfield/s3-encryption#10]
I was hoping to use the tests here to learn a little bit about the logic of the client but was immediately stymied by a missing `mock` dependency.  Initially I thought this was an omitted local module, but now I realized it is actually python `mock`.

**Comment by OAuthBringer** [comment]
https://github.com/boldfield/s3-encryption/blob/master/tests/test_envelope.py#L2

**Comment by boldfield** [comment]
Hey @neolytics,

Mock isn't part of the distribution dependencies, it's part of the dev dependencies.  You can install the dev dependencies as follows:

```
$ git clone git@github.com:boldfield/s3-encryption.git && cd s3-encryption
$ mkvirtualenv # Assuming you're using a python virtual environment
$ python setup.py dev
```

I'll wait to close this out until you confirm you got things working, thanks!

**Comment by OAuthBringer** [comment]
Confirmed.  I've never done a oublic release of a pypi package before.  I was unaware of the ability to create dilineations like that.  Very cool.  Thanks.
