### ISSUE TITLE
put_object failed with error botocore.exceptions.ParamValidationError: Parameter validation failed

### ISSUE THREAD

**Issue by imlocn** [boldfield/s3-encryption#8]
def encrypt_upload(bucket, filename):
    s3 = boto3.client('s3', region_name=REGION)
    encoded_key = s3.get_object(Bucket=bucket, Key=KEYFILE)

```
s3e = S3EncryptionClient(encryption_key=KEYFILE, region_name=REGION)
s3e.put_object(Body=myfile, Bucket=bucket, Key=KEYFILE)

# Fail at the following line
s3e.client.put_object(Body=encoded_key, Bucket=bucket, Key=KEYFILE + '.key')
```

**Comment by boldfield** [comment]
What version of `botocore` and `s3-encryption` are you using?

**Comment by boldfield** [comment]
Ah, I may be misinterpreting what you're trying to do, but it looks like you're trying to reference a file on-disk for `encryption_key`? This parameter needs to be string and so the path you're passing (`KEYFILE`) is being interpreted as the key itself and is failing validation.

**Comment by boldfield** [comment]
You can see how to request (and use) KMS encryption keys by referencing another one of my projects, `kms-secrets`.  It's still in a very rough state right now, but it wraps `s3-encryption` to provide a cli for uploading/downloading secret data to/from s3.  Specifically, see [this function](https://github.com/boldfield/kms-secrets/blob/master/kms-secrets#L62) for how to get the keys themselves.

**Comment by boldfield** [comment]
closing due to lack of response...
